---
version: '3'

x-healtcheck-settings: &healthcheck-settings
    interval: 20s
    timeout: 10s
    retries: 6
    start_period: 10s

services:
    banking-api:
        image: cosmtrek/air:latest
        env_file:
            - ./banking-api/.env
        volumes:
            - ./banking-api/:/go/src/github.com/plutus/banking-api
        working_dir: /go/src/github.com/plutus/banking-api
        ports:
            - 3000:3000
        depends_on:
            postgres:
                condition: service_healthy

    postgres:
        image: postgres:16.2
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql:delegated
            - ./env/postgres:/docker-entrypoint-initdb.d:cached
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            <<: *healthcheck-settings
    
volumes:
    postgres_data:
