definitions:
  definitions.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      updated_at:
        type: string
    type: object
  definitions.UserInput:
    properties:
      email:
        type: string
      name:
        type: string
    required:
    - email
    - name
    type: object
host: locahost:3000
info:
  contact: {}
  description: This is a API representing a simple banking system.
  title: Plutus Banking API
  version: "1.0"
paths:
  /healthz:
    get:
      description: Check service health condition
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Check service health
      tags:
      - health
  /user:
    post:
      description: Create a user in the system
      parameters:
      - description: user to create
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/definitions.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/definitions.User'
      summary: Create a user
      tags:
      - user
    put:
      description: Update a user in the system
      parameters:
      - description: id of user to update
        in: query
        name: id
        required: true
        type: string
      - description: user to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/definitions.UserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/definitions.User'
      summary: Update a user
      tags:
      - user
swagger: "2.0"
